development:
  adapter: redis
  url: <%= ENV['COSMOS_REDIS_URL'] || (ENV['COSMOS_DEVEL'] ? 'redis://127.0.0.1:6379/0' : 'redis://cosmos-redis:6379/0') %>
  channel_prefix: script_runner_api

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['COSMOS_REDIS_URL'] || (ENV['COSMOS_DEVEL'] ? 'redis://127.0.0.1:6379/0' : 'redis://cosmos-redis:6379/0') %>
  channel_prefix: script_runner_api
