development:
  adapter: redis
  url: <%= ENV['COSMOS_REDIS_URL'] || 'redis://127.0.0.1:6379/0' %>
  # The channel_prefix is used in scripts/run_script.rb to subscribe to the channel
  # and app/models/running_script.rb to publish to the channel
  channel_prefix: script-api

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['COSMOS_REDIS_URL'] || 'redis://127.0.0.1:6379/0' %>
  # The channel_prefix is used in scripts/run_script.rb to subscribe to the channel
  # and app/models/running_script.rb to publish to the channel
  channel_prefix: script-api
