# Base our rules on Rails
inherit_from:
  - https://raw.githubusercontent.com/rails/rails/master/.rubocop.yml
Style/StringLiterals:
  Enabled: false # Don't care about single vs double quoted strings
Layout/SpaceInsideBlockBraces:
  Enabled: false # We have a lot of {|block| block } vs this { |block| block }
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal # Rails uses the 'rails' style

# Our code has a lot of instances of the following:
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Style/AndOr:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
