env: JRUBY_OPTS=--debug COSMOS_DEVEL=true
dist: trusty
language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - jruby
  - 2.7
  - 2.6
before_install:
  - sudo apt-get install -y libgl1-mesa-dev
  - yes | gem update --system --force
  - gem install bundler
script: bundle exec rake build spec
