env: JRUBY_OPTS=--debug
language: ruby
sudo: false
cache: bundler
services:
  - postgresql
rvm:
  - jruby-9.2.5.0
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
before_install:
  - gem update --system
  - gem install bundler
script: bundle exec rake build spec
