language: ruby
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without development --jobs=3 --retry=3
rvm:
  - jruby-9.1.13.0
  - 2.4.2
  - 2.3.5
  - 2.2.8
script: bundle exec rake build spec
