environment:
  matrix:
    - ruby_version: 24-x64
    - ruby_version: 25-x64
    - ruby_version: 26-x64
    
cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - vendor\bundle -> appveyor.yml, Gemfile, cosmos.gemspec

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - bundle install --path vendor\bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake build spec

branches:
  only:
    - master
  except:
    - website
