environment:
  matrix:
    - ruby_version: 25-x64
    - ruby_version: 26-x64
    # - ruby_version: 27-x64  See https://help.appveyor.com/discussions/problems/28869-ruby-27-cant-find-gem

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - vendor\bundle -> appveyor.yml, Gemfile, cosmos.gemspec

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\MinGW\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - SET COSMOS_DEVEL=true
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake build spec

branches:
  only:
    - master
  except:
    - website
