coverage:
  status:
    # Disable patch reporting which we don't really use anyway
    # See https://docs.codecov.com/docs/commit-status#patch-status
    patch: off
    project:
      default:
        target: auto
        # Coverage can drop by 50% and still be a success (don't fail the build)
        threshold: 50%
      openc3-ruby:
        threshold: 50%
        paths:
          - openc3/openc3/lib
      frontend:
        threshold: 50%
        paths:
          - openc3-init
      api:
        threshold: 50%
        paths:
          - openc3-cmd-tlm-api
          - openc3-script-runner-api
