coverage:
  status:
    project:
      default:
        target: auto
        # Coverage can drop by 5% and still be a success
        threshold: 5%
      openc3-ruby:
        paths:
          - openc3
      frontend:
        paths:
          - openc3-init
      api:
        paths:
          - openc3-cmd-tlm-api
          - openc3-script-runner-api
