coverage:
  status:
    # Disable patch reporting which we don't really use anyway
    # See https://docs.codecov.com/docs/commit-status#patch-status
    patch: off
    project:
      default:
        target: auto
        # Coverage can drop by 5% and still be a success
        threshold: 5%
      openc3-ruby:
        threshold: 5%
        paths:
          - openc3
      frontend:
        threshold: 5%
        paths:
          - openc3-init
      api:
        threshold: 5%
        paths:
          - openc3-cmd-tlm-api
          - openc3-script-runner-api
