version: "3.9"

services:
  cosmos-redis:
    ports:
      - "127.0.0.1:6379:6379" # only allow localhost access to internal apis

  cosmos-minio:
    ports:
      - "127.0.0.1:9000:9000" # only allow localhost access to internal apis

  cosmos-cmd-tlm-api:
    ports:
      - "127.0.0.1:2901:2901" # only allow localhost access to internal apis

  cosmos-script-runner-api:
    ports:
      - "127.0.0.1:2902:2902" # only allow localhost access to internal apis
