development:
  adapter: redis
  url: <%= "redis://#{ENV['OPENC3_REDIS_USERNAME']}:#{ENV['OPENC3_REDIS_PASSWORD']}@#{ENV['OPENC3_REDIS_HOSTNAME']}:#{ENV['OPENC3_REDIS_PORT']}" %>
  # Doesn't appear to be used but it matches the script channel_prefix convention
  channel_prefix: openc3-api

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://#{ENV['OPENC3_REDIS_USERNAME']}:#{ENV['OPENC3_REDIS_PASSWORD']}@#{ENV['OPENC3_REDIS_HOSTNAME']}:#{ENV['OPENC3_REDIS_PORT']}" %>
  # Doesn't appear to be used but it matches the script channel_prefix convention
  channel_prefix: openc3-api
