---
api:
  dashboard: true
  insecure: true
entrypoints:
  web:
    address: ":80"
http:
  middlewares:
    removeFirst:
      replacePathRegex:
        regex: "^/([^/]*)/(.*)"
        replacement: "/$2"
  routers:
    web-router:
      rule: Host(`localhost`)
      service: service-web
    api-router:
      rule: PathPrefix(`/cosmos-api`)
      middlewares:
        - "removeFirst"
      service: service-api
    script-router:
      rule: PathPrefix(`/script-api`)
      middlewares:
        - "removeFirst"
      service: service-script
    tools-router:
      rule: PathPrefix(`/tools`)
      service: service-minio
  services:
    service-web:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:2910"
    service-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:2901"
    service-script:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:2902"
    service-minio:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:9000"
providers:
  file:
    filename: /etc/traefik/traefik.yaml
# log:
#  filePath: '/etc/traefik/traefik.log'
#  level: 'DEBUG'
#accessLog:
#  filePath: '/etc/traefik/access.log'
#  fields:
#    defaultMode: keep
#    headers:
#      defaultMode: keep
