---
entrypoints:
  web:
    address: ":80"
http:
  middlewares:
    removeFirst:
      replacePathRegex:
        regex: "^/([^/]*)/(.*)"
        replacement: "/$2"
    addToolsBase:
      replacePathRegex:
        regex: "^/(.*)"
        replacement: "/tools/base/$1"
    addIndex:
      replacePathRegex:
        regex: "(.*)/$"
        replacement: "$1/index.html"
  routers:
    web-router:
      rule: Host(`localhost`)
      middlewares:
        - "addToolsBase"
        - "addIndex"
      service: service-minio
    api-router:
      rule: PathPrefix(`/cosmos-api`)
      middlewares:
        - "removeFirst"
      service: service-api
    script-router:
      rule: PathPrefix(`/script-api`)
      middlewares:
        - "removeFirst"
      service: service-script
    tools-router:
      rule: PathPrefix(`/tools`)
      service: service-minio
  services:
    service-api:
      loadBalancer:
        servers:
          - url: "http://cosmos-cmd-tlm-api:2901"
    service-script:
      loadBalancer:
        servers:
          - url: "http://cosmos-script-runner-api:2902"
    service-minio:
      loadBalancer:
        servers:
          - url: "http://cosmos-minio:9000"
providers:
  file:
    filename: /etc/traefik/traefik.yaml
# api:
#   dashboard: true
#   insecure: trues
# log:
#  filePath: '/etc/traefik/traefik.log'
#  level: 'DEBUG'
#accessLog:
#  filePath: '/etc/traefik/access.log'
#  fields:
#    defaultMode: keep
#    headers:
#      defaultMode: keep
