development:
  adapter: redis
  url: <%= ENV['COSMOS_REDIS_URL'] || ENV['COSMOS_DEVEL'] ? 'redis://127.0.0.1:6379/0' : 'redis://cosmos_redis:6379/0' %>
  channel_prefix: cmd_tlm_api

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['COSMOS_REDIS_URL'] || ENV['COSMOS_DEVEL'] ? 'redis://127.0.0.1:6379/0' : 'redis://cosmos_redis:6379/0' %>
  channel_prefix: cmd_tlm_api
