# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# Reference environment variables: https://docs.github.com/en/actions/reference/environment-variables

name: Cosmos 5 API Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUBYGEMS_URL: https://rubygems.org
  BUNDLE_WITHOUT: development

jobs:
  cmd-tlm-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        env:
          COSMOS_DEVEL: ../cosmos
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: cosmos-cmd-tlm-api
      - name: Build cosmos
        run: bundle install; bundle exec rake build
        working-directory: cosmos
        env:
          COSMOS_DEVEL: ${GITHUB_WORKSPACE}/cosmos
      - name: Run cmd-tlm-api tests
        run: bundle exec rspec
        working-directory: cosmos-cmd-tlm-api
        env:
          COSMOS_DEVEL: ../cosmos

  script-runner-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        env:
          COSMOS_DEVEL: ../cosmos
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: cosmos-script-runner-api
      - name: Build cosmos
        run: bundle install; bundle exec rake build
        working-directory: cosmos
      - name: Run script-runner-api tests
        run: bundle exec rspec
        working-directory: cosmos-script-runner-api
        env:
          COSMOS_DEVEL: ../cosmos
