# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# Reference environment variables: https://docs.github.com/en/actions/reference/environment-variables

name: Cosmos 5 Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        env:
          RUBYGEMS_URL: https://rubygems.org
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: cosmos
      - name: Run tests
        run: bundle exec rake build spec
        working-directory: cosmos
        env:
          RUBYGEMS_URL: https://rubygems.org
          COSMOS_DEVEL: ${GITHUB_WORKSPACE}\cosmos
      - name: Run tests without extensions
        run: bundle exec rspec --tag no_ext
        working-directory: cosmos
        env:
          COSMOS_NO_EXT: 1
          RUBYGEMS_URL: https://rubygems.org
          COSMOS_DEVEL: ${GITHUB_WORKSPACE}\cosmos

  # docker-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: cosmos-control.sh build
  #       # This `shell` line is required to get around a known issue: https://github.com/actions/runner/issues/241#issuecomment-745902718
  #       shell: 'script -q -e -c "bash {0}"'
  #       run: ./cosmos-control.sh build

  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cosmos-control.sh start
        # This `shell` line is required to get around a known issue: https://github.com/actions/runner/issues/241#issuecomment-745902718
        shell: 'script -q -e -c "bash {0}"'
        run: ./cosmos-control.sh start
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chome
          working-directory: cypress
          wait-on: 'http://localhost:2900'
