# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Cosmos 5 Container Scans

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cosmos-ruby-scan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          scripts/linux/cosmos_setup.sh
          docker-compose -f compose.yaml -f compose-build.yaml build cosmos-ruby
      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
        with:
          image: "docker.io/ballaerospace/cosmosc2-ruby:latest"
          acs-report-enable: true
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  cosmos-base-scan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          scripts/linux/cosmos_setup.sh
          docker-compose -f compose.yaml -f compose-build.yaml build cosmos-base
      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@b08527d5ae7f7dc76f9621edb6e49eaf47933ccd
        with:
          image: "docker.io/ballaerospace/cosmosc2-base:latest"
          acs-report-enable: true
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  # Potentially scan these as well:
  # image: "ballaerospace/cosmosc2-traefik:latest"
  # image: "ballaerospace/cosmosc2-operator:latest"
  # image: "ballaerospace/cosmosc2-script-runner-api:latest"
  # image: "ballaerospace/cosmosc2-cmd-tlm-api:latest"
  # image: "ballaerospace/cosmosc2-redis:latest"
  # image: "ballaerospace/cosmosc2-minio-init:latest"
  # image: "ballaerospace/cosmosc2-node:latest"
