version: "3.7"

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    expose:
      - 24224
      - 24224/udp
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      discovery.type: single-node
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.6.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: bash -c "sleep 30; redis-server"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redis.log
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"
    #volumes:
    #  - type: bind
    #    source: /c/git/cosmosee/web/redis
    #    target: /opt/app/static

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    command: server /data
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: minio.log
        fluentd-async-connect: "true"
        fluentd-sub-second-precision: "true"
    #volumes:
    #  - type: bind
    #    source: /c/git/cosmosee/web/minio
    #    target: /opt/app/static
