version: "3.7"

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    expose:
      - 24224
      - 24224/udp
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      discovery.type: single-node
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.6.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
